version: '3.8'

services:
    database:
        image: 'postgres:12.3'
        ports:
            - '5433:5432'
        container_name: postgres-slopeDB
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: slopeDB
        volumes:
            - ../sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
            - ../sql/insert_data/Insert_Accomodation.sql:/docker-entrypoint-initdb.d/2-data.sql
            - ../sql/insert_data/Insert_Area.sql:/docker-entrypoint-initdb.d/2-data.sql
            - ../sql/insert_data/Insert_Helmets.sql:/docker-entrypoint-initdb.d/2-data.sql
            - ../sql/insert_data/Insert_Poles.sql:/docker-entrypoint-initdb.d/2-data.sql
            - ../sql/insert_data/Insert_Ski.sql:/docker-entrypoint-initdb.d/2-data.sql
            - ../sql/insert_data/Insert_Ski.sql:/docker-entrypoint-initdb.d/2-data.sql

    adminer:
        image: adminer
        restart: always
        ports:
            - 1234:8080
        depends_on:
            - "database"